In [2]:
import pickle
import os
import torch
import re

In [8]:
s = "cruise-===2020"
print(re.findall(r"cruise.*2020",s))

['cruise-===2020']


In [10]:
if re.findall(r"cruise*2020",s):
    print(True)

In [12]:
with open("mini_data/train/data_seq_500_features.pkl", "rb") as f:
    data = pickle.load(f)
data

{'seq_id': '500',
 'candidate': tensor([[-60., -60.],
         [-56., -60.],
         [-52., -60.],
         ...,
         [ 48.,  56.],
         [ 52.,  56.],
         [ 56.,  56.]]),
 'candidate_gt': tensor([[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
       

In [13]:

for k,v in data.items():
    print(k,v.shape if isinstance(v,torch.Tensor) else v)

seq_id 500
candidate torch.Size([900, 2])
candidate_gt torch.Size([900, 1])
offset_gt torch.Size([2])
target_gt torch.Size([2])
orig [257.64587 752.4582 ]
rot [[-0.25256166  0.9675808 ]
 [-0.9675808  -0.25256166]]
traj_num 45
lane_num 2
y torch.Size([60])
x torch.Size([792, 6])
cluster torch.Size([792])
identifier torch.Size([47, 2])


In [16]:
data['x']

tensor([[-1.7657e-02, -1.1478e+01,  2.2748e-03,  5.8934e-01,  0.0000e+00,
          0.0000e+00],
        [-1.5382e-02, -1.0889e+01,  2.6361e-03,  7.1108e-01,  1.0000e+00,
          0.0000e+00],
        [-1.2746e-02, -1.0178e+01,  1.5828e-03,  4.7626e-01,  2.0000e+00,
          0.0000e+00],
        ...,
        [-4.3091e+00,  3.7980e+01,  3.6912e-02,  1.9984e+00,  0.0000e+00,
          4.6000e+01],
        [-4.2961e+00,  3.9979e+01, -1.0837e-02,  1.9994e+00,  0.0000e+00,
          4.6000e+01],
        [-4.2954e+00,  4.1978e+01,  1.2110e-02,  1.9995e+00,  0.0000e+00,
          4.6000e+01]])

In [17]:
data['identifier']

tensor([[-1.7657e-02, -1.1478e+01],
        [-5.0236e+00, -9.3151e+01],
        [-4.8943e+00, -8.0728e+01],
        [-4.7578e+00, -6.3746e+01],
        [-4.9766e+00, -7.4869e+01],
        [ 2.3304e+00, -9.1436e+01],
        [ 2.3051e+00, -7.0842e+01],
        [ 2.9600e+00, -2.9011e+01],
        [-4.8851e+00, -2.5528e+01],
        [ 2.9373e+00, -3.3872e+01],
        [ 2.4834e+00, -6.5264e+01],
        [ 2.9215e+00, -2.8193e+00],
        [-3.4240e+00,  6.8146e+00],
        [ 3.0234e+00, -8.4207e+00],
        [-5.6211e+00, -5.7431e+01],
        [-4.3537e+00, -9.8477e+00],
        [ 2.8685e+00, -2.3560e+01],
        [-4.7025e+00, -1.5183e+01],
        [-4.5442e+00,  1.3051e+00],
        [ 2.9021e+00,  1.0425e+01],
        [ 2.9402e+00, -1.3217e+01],
        [ 2.9278e+00, -1.8541e+01],
        [-4.6183e+00, -4.3157e+00],
        [ 2.9783e+00,  5.0899e+01],
        [ 2.9928e+00,  2.2209e+01],
        [-4.6783e+00,  6.9613e+01],
        [-4.7714e+00,  3.9691e+01],
        [ 2.9990e+00,  6.196

In [18]:
data['cluster']

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12,
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 14, 14, 14, 14, 14, 14, 14, 